function [bandpass, delay] = myBand
%MYBAND Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
%
% Generated on: 13-Nov-2013 19:35:50
%

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 120;  % Sampling Frequency

Fstop1 = 0.2;             % First Stopband Frequency
Fpass1 = 0.3;             % First Passband Frequency
Fpass2 = 8;               % Second Passband Frequency
Fstop2 = 11;              % Second Stopband Frequency
Dstop1 = 0.1;             % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.1;             % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
bandpass = dfilt.dffir(b);

% get the delay (lag) caused by the filter (half the order)
if (exist('filtord')) % if newer MATLAB
    delay = round(filtord(b) / 2);
else % if older MATLAB
    delay = grpdelay(b); % returns an array (of all the same numbers)
    delay = delay(1); % so take just the first element
end;
% [EOF]
